### ISSUE TITLE
user-can-create-an-event

### ISSUE THREAD

**Issue by matt-cha** [matt-cha/plan-it#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Feature: User can create an event
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Fill out info for a form and create an event
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-02-20 at 12 24 01 PM](https://user-images.githubusercontent.com/113474295/220192404-fac89971-51c5-433b-af26-a1460f6e0d88.png)
![Screen Shot 2023-02-20 at 12 24 16 PM](https://user-images.githubusercontent.com/113474295/220192442-67d58309-360c-4efd-876a-cf944edfaeb7.png)

Look for a direct email to talk to 

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create a table events with columns name, details, eventId as the primary key
- [x] Update `data.sql` to insert into the events table the values from the form submitted

### ☁️ Server Tasks

- [x] Update `server/index.js` to use a post routing request that takes the values of name and details 
- [x] use SQL to insert the data into the database 
- [x] Query the database and then send the result back to the server
- [x] Catch for any errors
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

**Create**

- [x] Create a navbar with the create event button on the top right
- [x] Create a component for a form that allows user to input information for a form and submit

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
