### ISSUE TITLE
Feature: User can invite guests and manage guest list  

### ISSUE THREAD

**Issue by matt-cha** [matt-cha/plan-it#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can invite guests and manage guest list 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Add guests by name and phone number, using Twilio API to send SMS messages through a phone number with a link to the event

https://flatpickr.js.org/examples/
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-02-20 at 2 50 34 PM](https://user-images.githubusercontent.com/113474295/220209371-36f479ae-cac1-4316-beed-f8d1f77fe8a1.png)
Add desktop screen as well once done
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks
**Create**

- [ ] Create a component for a form that allows user to input information for a form
- [ ] Use flatpickr.js to allow user to select a start and end date
     - [ ] Prevent user from selecting an end date that is before the start date selected
- [ ] Integrate Google Maps API to display a map of the location entered into the field 
- [ ] Allow users to upload a cover photo / image for the event and display a preview of it

**View**
- [x] Display all events on the "home page" of the web app in a list going down 
- [x] Clicking the home button allows users to see all events 
- [x] Clicking new event button will go to the create new event form
- [x] Clicking on an individual event will move user to see all event details
- [x]  Twilio API to send text messages to phone number

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
